### ISSUE TITLE
Move (or copy) "Close all tabs from this domain" to tab context menu

### ISSUE THREAD

**Issue by trlkly** [mos3abof/firefox-power-close#9]
It's something you said you were doing, but I noticed you didn't have a formal issue for it. This way, when you finish you can mark an issue as "Fixed." It's really satisfying.

**Comment by mos3abof** [comment]
It seems that the current SDK does not support modifying the tabs context menu, at least that I am aware of. If you have any information that can help with this, please let me know.

Closing this issue for the moment.
